// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPNaClmWNL1GirFXTgTOVU0Cv6Z7vUXus',
    appId: '1:323633714883:web:0b3c269243aa528a067476',
    messagingSenderId: '323633714883',
    projectId: 'quizz-2937b',
    authDomain: 'quizz-2937b.firebaseapp.com',
    storageBucket: 'quizz-2937b.firebasestorage.app',
    measurementId: 'G-9HNCSNJ4SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpeEUuESUp3N4Z0M1K9JulrJPFGmsd_0',
    appId: '1:323633714883:android:67b6a8b5ef99d0af067476',
    messagingSenderId: '323633714883',
    projectId: 'quizz-2937b',
    storageBucket: 'quizz-2937b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_GHVvR2N18gBafJUbmZbtfbKbkwT29M',
    appId: '1:323633714883:ios:89b3c380a68f04cb067476',
    messagingSenderId: '323633714883',
    projectId: 'quizz-2937b',
    storageBucket: 'quizz-2937b.firebasestorage.app',
    iosBundleId: 'com.example.quizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd_GHVvR2N18gBafJUbmZbtfbKbkwT29M',
    appId: '1:323633714883:ios:89b3c380a68f04cb067476',
    messagingSenderId: '323633714883',
    projectId: 'quizz-2937b',
    storageBucket: 'quizz-2937b.firebasestorage.app',
    iosBundleId: 'com.example.quizz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPNaClmWNL1GirFXTgTOVU0Cv6Z7vUXus',
    appId: '1:323633714883:web:d15e3ba845c88916067476',
    messagingSenderId: '323633714883',
    projectId: 'quizz-2937b',
    authDomain: 'quizz-2937b.firebaseapp.com',
    storageBucket: 'quizz-2937b.firebasestorage.app',
    measurementId: 'G-XMS2K3SY5G',
  );
}
